# Generated by Django 6.0.7 on 2026-09-10 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('react', 'React'), ('js', 'JavaScripts'), ('aws', 'AWS'), ('gcp', 'GCP')], max_length=50, unique=True, verbose_name='Course')),
                ('crCat', models.CharField(choices=[('coding', 'Coding'), ('cloud', 'Cloud')], max_length=15, verbose_name='Category')),
                ('dur', models.IntegerField(help_text='Duration Should be in Months', verbose_name='Duration')),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('DOJ', models.DateField()),
                ('aboutMe', models.TextField(max_length=500)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
            ],
        ),
    ]
