# Generated by Django 6.0.7 on 2026-09-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='cardNum',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
