# Generated by Django 6.0.7 on 2026-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('join_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
