# Generated by Django 6.0.7 on 2026-08-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('react', 'React'), ('js', 'JavaScripts'), ('aws', 'AWS'), ('gcp', 'GCP')], default='js', max_length=50)),
                ('crCat', models.CharField(choices=[('coding', 'Coding'), ('cloud', 'Cloud')], max_length=15)),
                ('dur', models.IntegerField(help_text='Duration Should be in Months')),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=35)),
                ('contact', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField()),
                ('joined_at', models.DateField()),
                ('course', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student3',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=35)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('loginTime', models.TimeField()),
                ('signUpAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('studentStatus', models.BooleanField(default=True)),
                ('projectURL', models.URLField()),
                ('aboutMe', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('DOJ', models.DateField()),
                ('aboutMe', models.TextField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
            ],
        ),
    ]
