# Generated by Django 6.0.7 on 2026-08-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=35)),
                ('contact', models.IntegerField(max_length=10)),
                ('create_at', models.DateTimeField()),
                ('joined_at', models.DateField()),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
