# Generated by Django 6.0.7 on 2026-09-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('react', 'React'), ('js', 'JavaScripts'), ('aws', 'AWS'), ('gcp', 'GCP')], max_length=50, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='crCat',
            field=models.CharField(choices=[('coding', 'Coding'), ('cloud', 'Cloud')], max_length=15, verbose_name='Category'),
        ),
    ]
