# Generated by Django 6.0.7 on 2026-08-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student2'),
    ]

    operations = [
        migrations.CreateModel(
            name='student3',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=35)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('loginTime', models.TimeField()),
                ('signUpAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('studentStatus', models.BooleanField(default=True)),
                ('projectURL', models.URLField()),
                ('aboutMe', models.TextField(max_length=500)),
            ],
        ),
    ]
