# Generated by Django 6.0.7 on 2026-09-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_course_cname_alter_course_crcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('react', 'React'), ('js', 'JavaScripts'), ('aws', 'AWS'), ('gcp', 'GCP')], max_length=50, unique=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dur',
            field=models.IntegerField(help_text='Duration Should be in Months', verbose_name='Duration'),
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNum', models.CharField(max_length=10, unique=True)),
                ('issue_Date', models.DateField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
