# Generated by Django 6.0.7 on 2026-09-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_course_cname_alter_course_dur_idcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stduent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=25)),
                ('courses', models.ManyToManyField(to='app1.course1')),
            ],
        ),
    ]
