# Generated by Django 6.0.7 on 2026-09-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_course1_stduent1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stduent1',
            new_name='Student1',
        ),
    ]
