# Generated by Django 6.0.7 on 2026-09-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_stduent1_student1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=3)),
                ('student_id', models.CharField(max_length=4)),
                ('sname', models.CharField(max_length=10)),
            ],
        ),
    ]
